# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  host: localhost
  timeout: 5000
  username: user
  password: password

test:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
  username: user
  password: password

production:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
  username: user
  password: password
